---
# Echo Service v1 (Weight: 70)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service
      version: v1
  template:
    metadata:
      labels:
        app: echo-service
        version: v1
      annotations:
        io.cilium.service/weight: "70"  # <-- Weight annotation
    spec:
      containers:
      - name: echo
        image: jmalloc/echo-server:0.2.0
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "V1"

---
# Echo Service v2 (Weight: 30)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service
      version: v2
  template:
    metadata:
      labels:
        app: echo-service
        version: v2
      annotations:
        io.cilium.service/weight: "50"  # <-- Weight annotation
    spec:
      containers:
      - name: echo
        image: jmalloc/echo-server:0.2.0
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: "V2"

---
# Service (combines v1 and v2)
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  annotations:
    io.cilium.lb-algorithm: "wrr" 
    io.cilium.lb-weight.echo-service-v1: "70"
    io.cilium.lb-weight.echo-service-v2: "30" # <-- Set Load Balancing algorithm to WRR
spec:
  selector:
    app: echo-service  # Selects both v1 and v2
  ports:
  - port: 8080
    targetPort: 8080
